[versions]
springBoot = "3.4.2"
dependencyManagement = "1.1.7"
kotlinKapt = "2.1.0"
kotlinJvm = "1.9.25"
kotlinSpring = "2.1.0"
java = "21"
rsa = "1.1.5"

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinKapt" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlinSpring" }
